# Default Model
model: deepseek:deepseek-chat

# Config
stream: true
keybindings: vi
editor: nvim
wrap: no
wrap_code: false

# Write in Markdown
name: markdown
prompt: convert INPUT to markdown

# AI Config
clients:
- type: openai-compatible
  name: deepseek
  api_base: https://api.deepseek.com/v1
  apiKey: $DEEPSEEK_API_KEY
- type: openai
  name: openai
  api_base: https://api.openai.com/v1
  apiKey: $OPENAI_API_KEY
